package main

import (
	"fmt"
	"github.com/thedevsaddam/gojsonq/v2"
	"io/ioutil"
	"os"
)

type Data struct {
	Id           string `json:"_id,omitempty"`
	Uid          string `json:"uid,omitempty"`
	Tel          string `json:"tel,omitempty"`
	Name         string `json:"name,omitempty"`
	DiTag        string `json:"di_tag,omitempty"`
	Addr         string `json:"addr,omitempty"`
	ApiAdminInfo AutoGenerated `json:"api_admin_info,omitempty"`
	UpdatedAt    string `json:"updated_at,omitempty"`
}

type AutoGenerated struct {
	AreaName string `json:"area_name"`
	CityName string `json:"city_name"`
	ProvName string `json:"prov_name"`
}


func main() {
	f, err := os.OpenFile("./examples/jsonOp/transfer/data.json", os.O_RDWR, 0666)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	bs, err := ioutil.ReadAll(f)
	if err != nil {
		panic(err)
	}
	jList := gojsonq.New().JSONString(string(bs))


	fmt.Println(jList.Find("result.[0].name"))

}
